### ISSUE TITLE
Bootstrap Onepager

### ISSUE THREAD

**Issue by hansnolte** [tylerjpeterson/ios-inner-height#1]
Hi tylerjpeterson,

looks interesting!

I also have the problem with the iPhone in the landscape mode.
Navigation is hidden by the address bar.

Can you please tell a javascript beginner how I can integrate it into a bootstrap onepager?
https://www.valtcon.de/test/

Thanks in advance
Hans

**Comment by tylerjpeterson** [comment]
@hansnolte - Sure, I can provide more examples in the docs. In the meantime, you can check out the [example js file](https://github.com/tylerjpeterson/ios-inner-height/blob/master/test/examples/js/demo.js) in the `tests` directory. Note, that file would need to be built (by [`browserify`](http://browserify.org/) for example) before being consumed by the browser.

I can also drop a built version of this to the package for build-less use. Have a feeling that's really what you're after.

**Comment by hansnolte** [comment]
Hi tylerjpeterson,

you are absolutely right, a ready build would be just right for a beginner like me.

Many thanks
Hans

**Comment by tylerjpeterson** [comment]
See updated README.md and built file for resolution.
