### ISSUE TITLE
This is great!

### ISSUE THREAD

**Issue by hamblyfreeman** [tylerjpeterson/ios-inner-height#4]
No issues... Honestly, what a shit hot solution! Thanks for coming up with this!

Is this OK for productions sites? No known bugs?

**Comment by tylerjpeterson** [comment]
@hamblyfreeman - you're welcome! ...and sorry for the slow response. 

As for whether or not it's safe for production, I believe it should be. I can't get too specific, but it has been deployed successfully on a site that receives 8 figures worth of traffic daily - and we have had zero reported issues thus far from users and our QA team.

**Comment by hamblyfreeman** [comment]
Yep, I've had good experiences with it thus far.

Thanks again!

**Comment by hamblyfreeman** [comment]
In case you wondered, this has been used here: https://aeonik.co.uk/

**Comment by hensmith** [comment]
Bumping this thread just to add another thank you! ❤️
